# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app test-003

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    environment:
      name: 'test-003'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://cradonamingtoolfysqsphyi4vus.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_4f0e76adcc0c478ea7f8ab0867c03855 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_7a77b2e5002443399e0e9e2500f4ada9 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: cradonamingtoolfysqsphyi4vus.azurecr.io/azuredevopsnamingtool:latest,cradonamingtoolfysqsphyi4vus.azurecr.io/azuredevopsnamingtool:${{ github.sha }}
        #file: ./Dockerfile
        context: ./src/AzureDevOpsNaming.Tool

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'test-003'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'app-adonamingtool-fysqsphyi4vus'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_fc0208912bab4c238a32c944268e34d2 }}
        images: 'cradonamingtoolfysqsphyi4vus.azurecr.io/azuredevopsnamingtool:${{ github.sha }}'
